deploy:
  needs: staging
  environment:
    name: production
    url: ${{ steps.deploy_production.outputs.webapp-url }}
  name: Deploy to production
  runs-on: ubuntu-latest
  steps:
  # Download artifacts
  - name: Download artifacts
    uses: actions/download-artifact@v2
    with:
      name: webapp
 
  # Deploy to App Service Linux
  - name: Deploy to Azure WebApp
    id: deploy_production
    uses: azure/webapps-deploy@v2
    with:
      app-name: ${{ env.AZURE_WEBAPP_NAME }}
      publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
